### ISSUE TITLE
Add fields to systems.yaml

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteUtils.jl#22]
Add the following fields to systems.yaml

```yaml
    depower:   25.0        # initial depower settings    [%]

solver:
    abs_tol: 0.0006        # absolute tolerance of the DAE solver [m, m/s]
    rel_tol: 0.001         # relative tolerance of the DAE solver [-]
    max_iter:  200         # max number of iterations of the steady-state-solver
    
kite:
    physical_mode: "KPS4"
    version: 1
```
